service: ocr-scanner

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

plugins:
  - serverless-offline

functions:
  getImageText:
    handler: handler.getImageText
    events:
      - http:
          path: image-text
          method: post
          cors: true
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
